name: build and push docker image
on:
  Push:
      branch:
       -main
jobs: 
    build:
     runs-on : ubuntu-latest

steps:
     - name: checkout latest
       uses: actions/checkout@v3
     

      -name: log in to Docker Hub
       uses: actions/checkout@v2
       
       with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }} 

name: build and push Docker Image
uses: docker/build-push-actions@v4
with:
context: .
push: true
tags: ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest